INSERT INTO public.clientes (nome, cidade, uf) VALUES('Leonardo', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Solange', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Gabriel', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Yuri', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Ana Luísa', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Gabriele', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Edson', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Inaldo', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Cleonice', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Gustavo', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Daniella', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Cláudia', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Osvaldo', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Fátima', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Rafael', 'Rio de Janeiro', 'RJ');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Priscila', 'Florianópolis', 'SC');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('João', 'Florianópolis', 'SC');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Pedro', 'Florianópolis', 'SC');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Maria Quitéria', 'Florianópolis', 'SC');
INSERT INTO public.clientes (nome, cidade, uf) VALUES('Luiz', 'Teresópolis', 'RJ');


INSERT INTO public.produtos (descricao, valor_venda) VALUES('Cadeira', 350);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Mesa', 1200);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Sofá', 1100);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Armário de casal', 1300);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Janela', 290);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Cimento', 28);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Tijolo', 1.20);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Vaso sanitário', 670);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Argamassa', 30);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Colher de pedreiro', 12);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Piso porcelanato', 47);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Tanque', 180);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Porta', 900);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Pia de cozinha', 400);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Pia de banheiro', 560);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Armário de cozinha', 385);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Cama de casal', 1400);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Cama de solteiro', 790);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('Espelho de banheiro', 210);
INSERT INTO public.produtos (descricao, valor_venda) VALUES('ventilador de teto', 150);